/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-08-01 03:09:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.supermarkethibernate.service.UsuarioService;
import com.supermarkethibernate.model.Usuario;

public final class editar_005fusuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.supermarkethibernate.service.UsuarioService");
    _jspx_imports_classes.add("com.supermarkethibernate.model.Usuario");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    // Verificar si el usuario está en la sesión
    Usuario usuario = (Usuario) session.getAttribute("usuario");

    if (usuario == null) {
        // Si no hay usuario en la sesión, redirigir al login
        response.sendRedirect("index.jsp"); // Cambia "index.jsp" por la página de login
        return;
    }
    
    // Obtener el ID del usuario que se va a editar
    int id = Integer.parseInt(request.getParameter("id"));
    UsuarioService usuarioService = new UsuarioService();
    usuario = usuarioService.obtenerUsuarioPorId(id);

    if ("POST".equalsIgnoreCase(request.getMethod())) {
        String ndocumento = request.getParameter("ndocumento");
        String nombre = request.getParameter("nombre");
        String apellido = request.getParameter("apellido");
        String nombreUsuario = request.getParameter("nombre_usuario");
        String contrasenia = request.getParameter("contrasenia");

        usuarioService.actualizarUsuario(id, ndocumento, nombre, apellido, nombreUsuario, contrasenia);
        response.sendRedirect("gestion_usuarios.jsp");
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://rawcdn.githack.com/Carlos-Crz/Repo_Code-Supermarket/7d11893b05e7978a38cfa19edb448502f80f48ec/CSS/styleguide.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://rawcdn.githack.com/Carlos-Crz/Repo_Code-Supermarket/1e24c24f0e12729f4d1cfabeb4164a44280ea17b/CSS/style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\n");
      out.write("    <link rel=\"shortcut icon\" href=\"https://rawcdn.githack.com/Carlos-Crz/Repo_Code-Supermarket/56d216c5ce1ce572bc99c2fd85df7bc3b42c732f/Imagenes/Icon.png\" type=\"image/x-icon\">\n");
      out.write("    <title>Gestión de Usuarios - Editar </title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- HEADER --> \n");
      out.write("    <header class=\"Header\">\n");
      out.write("        <div class=\"Header__menu\" onclick=\"toggleSidebar()\">\n");
      out.write("            <span class=\"material-symbols-outlined\" >menu</span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"Header__slidebar\">\n");
      out.write("            <img class=\"img\" src=\"https://rawcdn.githack.com/Carlos-Crz/Repo_Code-Supermarket/56d216c5ce1ce572bc99c2fd85df7bc3b42c732f/Imagenes/Logotipo.svg\" alt=\"Logotipo\"/>\n");
      out.write("            <span class=\"material-symbols-outlined\">account_circle</span>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- END HEADER  -->\n");
      out.write("    \n");
      out.write("    <div class=\"main-container\">\n");
      out.write("\n");
      out.write("        <!-- SLIDEBAR -->\n");
      out.write("        <aside class=\"slidebar\">\n");
      out.write("            <nav class=\"slidebar__nav\">\n");
      out.write("            <ul>\n");
      out.write("                <li class=\"slidebar__item\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">\n");
      out.write("                        home\n");
      out.write("                    </span>\n");
      out.write("                    <a href=\"dashboard.jsp\">Dashboard</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"slidebar__item\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">\n");
      out.write("                        category\n");
      out.write("                    </span>\n");
      out.write("                    <a href=\"\">Gestión de categorías</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"slidebar__item\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">\n");
      out.write("                        inventory_2\n");
      out.write("                    </span>\n");
      out.write("                    <a href=\"\">Gestión de productos</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"slidebar__item\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">\n");
      out.write("                        credit_card\n");
      out.write("                    </span>\n");
      out.write("                    <a href=\"\">Gestión de cajas</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"slidebar__item\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">\n");
      out.write("                        local_shipping\n");
      out.write("                    </span>\n");
      out.write("                    <a href=\"\">Gestión de proveedores</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"slidebar__item\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">\n");
      out.write("                        supervisor_account\n");
      out.write("                    </span>\n");
      out.write("                    <a href=\"\">Gestión de clientes</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"slidebar__item\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">\n");
      out.write("                        payments\n");
      out.write("                    </span>\n");
      out.write("                    <a href=\"\">Gestión de ventas</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"slidebar__item\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">\n");
      out.write("                        account_circle\n");
      out.write("                    </span>\n");
      out.write("                    <a href=\"gestion_usuarios.jsp\">Gestión de usuarios</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"sidebar_colp\">\n");
      out.write("                <ul>\n");
      out.write("                    <li>\n");
      out.write("                        <span class=\"material-symbols-outlined\">logout</span>\n");
      out.write("                        <a href=\"logout\">Cerrar Sesion</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </aside>\n");
      out.write("        <!-- END SLIDEBAR -->\n");
      out.write("        \n");
      out.write("        <!-- CONTENIDO -->\n");
      out.write("        <main class=\"conteiner\">\n");
      out.write("            <div class=\"title-description\">\n");
      out.write("                <h1 class=\"title\">Editar Usuario</h1>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <form class=\"inputs\"  method=\"post\">\n");
      out.write("                <h3>Información del Usuario</h3>\n");
      out.write("                <div>\n");
      out.write("                    <label class=\"inputs_label\" for=\"Ndoc\">Número de documento</label>\n");
      out.write("                    <input id=\"Ndoc\" class=\"inputs_input\" type=\"text\" name=\"ndocumento\" value=\"");
      out.print( usuario.getNdocumento() );
      out.write("\" required>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <label class=\"inputs_label\" for=\"nom\">Nombre</label>\n");
      out.write("                    <input id=\"nom\" class=\"inputs_input\" type=\"text\" name=\"nombre\" value=\"");
      out.print( usuario.getNombre() );
      out.write("\" required>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <label class=\"inputs_label\" for=\"Ape\">Apellidos</label>\n");
      out.write("                    <input id=\"Ape\" class=\"inputs_input\" type=\"text\" name=\"apellido\" value=\"");
      out.print( usuario.getApellido() );
      out.write("\" required>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <label class=\"inputs_label\" for=\"Nuser\">Nombre de usuario</label>\n");
      out.write("                    <input id=\"Nuser\" class=\"inputs_input\" type=\"text\" name=\"nombre_usuario\" value=\"");
      out.print( usuario.getNombreUsuario() );
      out.write("\" required>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <label class=\"inputs_label\" for=\"pass\">Contraseña</label>\n");
      out.write("                    <input id=\"pass\" class=\"inputs_input\" type=\"text\" name=\"contrasenia\" value=\"");
      out.print( usuario.getContrasenia() );
      out.write("\" required>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"button-container\">\n");
      out.write("                    <button class=\"Nbutton Can\" onclick=\"window.location.href='gestion_usuarios.jsp'\" type=\"button\">Cancelar</button>\n");
      out.write("                    <button class=\"Nbutton\" type=\"submit\">Actualizar Usuario</button> \n");
      out.write("                </div>\n");
      out.write("            </form>                 \n");
      out.write("        </main>\n");
      out.write("        <!-- END CONTENIDO --> \n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        function toggleSidebar() {\n");
      out.write("            document.querySelector('.slidebar').classList.toggle('active');\n");
      out.write("            document.querySelector('.conteiner').classList.toggle('expanded');\n");
      out.write("        }\n");
      out.write("        document.querySelectorAll('li').forEach(function(li) {\n");
      out.write("            li.addEventListener('click', function() {\n");
      out.write("                const a = li.querySelector('a');\n");
      out.write("                if (a) {\n");
      out.write("                    window.location.href = a.href;\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
